"""create onboarding_job and provisioning_task

Revision ID: 42d2da123f4f
Revises:
Create Date: 2026-09-22 11:52:14.697137

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "42d2da123f4f"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "onboarding_job",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("employee_id", sa.String(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("personal_email", sa.String(), nullable=False),
        sa.Column("department", sa.String(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("company_email", sa.String(), nullable=True),
        sa.Column("dedupe_key", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "in_progress",
                "completed",
                "partial_success",
                "failed",
                name="jobstatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_onboarding_job_dedupe_key"),
        "onboarding_job",
        ["dedupe_key"],
        unique=True,
    )
    op.create_table(
        "provisioning_task",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("onboarding_job_id", sa.Uuid(), nullable=False),
        sa.Column(
            "service",
            sa.Enum("google_workspace", "slack", "github", name="servicename"),
            nullable=False,
        ),
        sa.Column(
            "kind", sa.Enum("identity", "invitation", name="taskkind"), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "in_progress",
                "retrying",
                "completed",
                "failed",
                "skipped",
                name="taskstatus",
            ),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("account_email", sa.String(), nullable=True),
        sa.Column("details", sa.String(), nullable=True),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["onboarding_job_id"],
            ["onboarding_job.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("provisioning_task")
    op.drop_index(op.f("ix_onboarding_job_dedupe_key"), table_name="onboarding_job")
    op.drop_table("onboarding_job")
    # ### end Alembic commands ###
